package org.Compiladores.Kotlin



enum class TokenType{
    //Funciones
    EOF, CLASS,  ELSE, FOR, FUNCTION, IF, NULL, PRINT,

    //
    RETURN, SUPER, THIS, TRUE, FALSE, WHILE, VAR, AND, OR, NEWLINE, LETTER,


    NUMBER,
    STRING,
    IDENTIFIER,
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_BRACE,
    RIGHT_BRACE,
    RIGHT_CORCH,
    LEFT_CORCH,
    COMMA,
    DOT,
    SEMICOLON,
    MINUS,
    PORCENT,
    UNDERSCORE,
    INTERROGATIVE,
    MINUS_EQUAL,
    PLUS,
    PLUS_EQUAL,
    MULTIPLY,
    MULTIPLY_EQUAL,
    DIVIDE,
    DIVIDE_EQUAL,
    MOD,
    MOD_EQUAL,
    NOT,
    EQUAL,
    NOT_EQUAL,
    ASSIGN,
    LESS,
    LESS_EQUAL,
    GREATER,
    GREATER_EQUAL


   
}